// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYacq72qpHKwY_75nbMLjJB8eCSiH3A-s',
    appId: '1:84676724997:web:cc9b2c87ccedddd4794f6c',
    messagingSenderId: '84676724997',
    projectId: 'med4-6ff0c',
    authDomain: 'med4-6ff0c.firebaseapp.com',
    storageBucket: 'med4-6ff0c.appspot.com',
    measurementId: 'G-K1W703MKLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2e5fypbvbLIDWZIyUK1xYNh5RwTUzso',
    appId: '1:84676724997:android:9de9c5a71bdc574b794f6c',
    messagingSenderId: '84676724997',
    projectId: 'med4-6ff0c',
    storageBucket: 'med4-6ff0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_41camXw7eXpZ8u7oMcMj-iDNCFrC0Q',
    appId: '1:84676724997:ios:3fcc8fe05f762597794f6c',
    messagingSenderId: '84676724997',
    projectId: 'med4-6ff0c',
    storageBucket: 'med4-6ff0c.appspot.com',
    iosBundleId: 'com.example.midecinelocator3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_41camXw7eXpZ8u7oMcMj-iDNCFrC0Q',
    appId: '1:84676724997:ios:3fcc8fe05f762597794f6c',
    messagingSenderId: '84676724997',
    projectId: 'med4-6ff0c',
    storageBucket: 'med4-6ff0c.appspot.com',
    iosBundleId: 'com.example.midecinelocator3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYacq72qpHKwY_75nbMLjJB8eCSiH3A-s',
    appId: '1:84676724997:web:90d97ee744bb262d794f6c',
    messagingSenderId: '84676724997',
    projectId: 'med4-6ff0c',
    authDomain: 'med4-6ff0c.firebaseapp.com',
    storageBucket: 'med4-6ff0c.appspot.com',
    measurementId: 'G-5CCH7XVZ82',
  );

}